# -*- coding: utf-8 -*-
"""Coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSlFHlLBLzJC0rg5vaB6Uy-6LJXpEdUq
"""

def sum_of_multiples(number):
    if number < 0:
        return 0
    return sum(n for n in range(number) if n % 3 == 0 or n % 5 == 0)


def to_camel_case(text):
    words = text.replace("-", "_").split("_")
    return words[0] + "".join(word.capitalize() for word in words[1:])


def remove_vowels(string):
    return "".join(c for c in string if c.lower() not in "aeiou")


def order_words(sentence):
    return " ".join(sorted(sentence.split(), key=lambda w: sorted(w)))


def sort_odd_numbers(arr):
    odds = sorted([n for n in arr if n % 2 != 0])
    odd_index = 0
    return [odds[odd_index] if n % 2 != 0 else n for n in arr]



print(sum_of_multiples(10))
print(to_camel_case("the-stealth-warrior"))
print(remove_vowels("This website is for losers LOL!"))
print(order_words("is2 Thi1s T4est 3a"))
print(sort_odd_numbers([5, 8, 6, 3, 4]))